<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:07:43.
 */
class app_integranteModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var app_integranteModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new app_integranteModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers app_integranteModel::inserir
     * @todo   Implement testInserir().
     */
    public function testInserir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app_integranteModel::editar
     * @todo   Implement testEditar().
     */
    public function testEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app_integranteModel::paginate
     * @todo   Implement testPaginate().
     */
    public function testPaginate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app_integranteModel::apagar
     * @todo   Implement testApagar().
     */
    public function testApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
